let friends = [];

function add() {
    let friendName = document.getElementById('nome-amigo').value;
    if(friendName === '') {
        alert('Digite um nome')
        return;
    }
    friends.push(friendName)
    document.getElementById('lista-amigos').textContent = friends.join(', ');
     // Clear the input field after adding friend name
    document.getElementById('nome-amigo').value = '';
}

function draw() {
    document.getElementById('nome-amigo').value = '';
    // Get the div where i need to populate the pairs that are draw
    let drawFriends = document.querySelector('.prizeDraw__container');
    // Clear any previous elements inside it
    drawFriends.textContent = '';
    // Check if we have at least 2 people so we can make a pair
     if (friends.length < 2) {
        alert('Precisa adicionar ao menos dois nomes!');
        return;
    }

    let shuffledFriends = shuffle(friends); // Shuffle the array
    // Create a new air to pair people
    let pairs = [];
    // Loop to go from start 0 to array.lenght-1
    for(let i = 0; i < shuffledFriends.length; i++) {
        // Pair the current index to the next one and check with modulo if you are at the end so you can pair the last with the first
        let pairIndex = (i + 1) % shuffledFriends.length;
        // push the pair to the array
        pairs.push(`${shuffledFriends[i]} -> ${shuffledFriends[pairIndex]}`);
        // Create a new <p> to start manipulating the DOM to display each pair
        let pairElement = document.createElement('p');
        pairElement.textContent = pairs[i];
        drawFriends.appendChild(pairElement);
    }
}

function reset() {
    friends = [];
    document.querySelector('.friends__container').textContent = "";
    document.querySelector('.prizeDraw__container').textContent = '';
    document.getElementById('nome-amigo').value = '';
}

// Fisher-Yates Shuffle swapping i starting at the end of the array with a random j index generated by math.random
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
    return array;   
  
}